# Project information
site_name: KIDO Documentation
repo_url: https://github.com/dartsim/dart.git
repo_name: GitHub
site_description: Kinematics, Dynamics and Optimization Library for Animation and Robotics
# site_favicon: null  # todo: add kido.ico
copyright: ï»¿Copyright (c) 2011-2015, Georgia Tech Research Corporation

# Build directories
theme: readthedocs
docs_dir: docs/readthedocs

pages:
- Home: 'index.md'
- Tutorials:
    - 'Introduction': 'tutorials/introduction.md'
    - 'Pendulum': 'tutorials/multi-pendulum.md'
    - 'Collisions' : 'tutorials/collisions.md'
    - 'Manipulator': 'tutorials/dominoes.md'
    - 'Biped': 'tutorials/biped.md'
