# https://help.github.com/en/articles/workflow-syntax-for-github-actions

name: Trigger Build Farm

on:
  push:
    branches:
      - dart8/main
  schedule:
    # Run at 09:00 UTC (02:00 PDT) everyday
    - cron: "0 9 * * *"

jobs:
  build_farm_on_push:
    if: github.event_name == 'push'
    name: Trigger Build Farm
    runs-on: ubuntu-latest
    steps:
      - name: Send request to dartsim/dart-build-farm to build a commit
        run: |
          curl -X POST https://api.github.com/repos/dartsim/dart-build-farm/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.ACCESS_TOKEN }} \
          --data '{"event_type": "Build Commit", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'", "ref": "'"$GITHUB_REF"'" }}'
  build_farm_on_schedule:
    if: github.event_name == 'schedule'
    name: Trigger Build Farm
    runs-on: ubuntu-latest
    steps:
      - name: Send request to dartsim/dart-build-farm to build dart8/main
        run: |
          curl -X POST https://api.github.com/repos/dartsim/dart-build-farm/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.ACCESS_TOKEN }} \
          --data '{"event_type": "Build Commit", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'", "ref": "dart8/main" }}'
