name: Update Lock Files

permissions:
  contents: write
  pull-requests: write

on:
  workflow_dispatch:
  schedule:
    - cron: 0 5 * * SAT # Runs at 05:00, on every Staturday

jobs:
  pixi-update:
    name: Maintenance | Update pixi.lock (${{ matrix.base }})
    concurrency:
      group: ${{ github.workflow }}-${{ matrix.base }}
      cancel-in-progress: false
    runs-on: ubuntu-latest
    strategy:
      matrix:
        base: [main, release-6.16]
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ matrix.base }}
      - name: Set up pixi
        uses: prefix-dev/setup-pixi@v0.9.3
        with:
          cache: false
          post-cleanup: ${{ !contains(runner.labels, 'dartsim') }}
          run-install: false
      - name: Update lockfiles
        run: |
          pixi global install pixi-diff-to-markdown
          pixi update --json --no-install | pixi-diff-to-markdown >> diff.md
      - name: Create pull request
        uses: peter-evans/create-pull-request@v8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update pixi lockfile
          title: Update pixi lockfile
          body-path: diff.md
          branch: update-pixi-${{ matrix.base }}
          base: ${{ matrix.base }}
          labels: pixi
          delete-branch: true
          add-paths: pixi.lock
